# Generated by Django 3.0.9 on 2020-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='note', max_length=200),
            preserve_default=False,
        ),
    ]
