# Generated by Django 3.0.9 on 2020-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200907_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin_content',
            field=models.TextField(blank=True),
        ),
    ]
