# Generated by Django 3.0.9 on 2020-09-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='isRead',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
