# Generated by Django 3.0.9 on 2020-09-14 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactus_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 2, 11, 9, 494368, tzinfo=utc)),
        ),
    ]
