# Generated by Django 3.0.9 on 2020-09-14 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200914_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 14, 1, 34, 877417, tzinfo=utc)),
        ),
    ]
