# Generated by Django 3.0.9 on 2020-09-14 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200914_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 14, 8, 5, 956206, tzinfo=utc)),
        ),
    ]
